routes/web.php
<?php


Route::get('/', function () {
    return view('login');
})->name('home');

Route::post('/login', 'HomeController@login')->name('login');
Route::get('/register', 'HomeController@resgister')->name('register');
Route::post('/logout', 'HomeController@logout')->name('logout');

Route::post('/login_hospede', 'UserController@login_hospede')->name('hospede');

Route::group(['prefix' => 'admin', 'middleware'=>['auth', 'admin']], function() {
    Route::get('/', 'HomeController@indexAdmin');
    Route::resource('room', 'RoomController');
    Route::resource('user', 'UserController');
    Route::post('/photo/store', 'PhotoController@store');
    Route::get('/photo/history', 'PhotoController@history');
    Route::post('/photo/index/{id}', 'PhotoController@index');
    Route::resource('photo', 'PhotoController');
});

Route::group(['prefix' => 'guest', 'middleware'=>['auth', 'hospede']], function() {
    Route::get('/settings','HomeController@settings')->name('settings');
    Route::get('/', 'HomeController@indexGuest');

});

resources/views/admin/createRoom.blade.php
@extends('layouts.app')
@section('title','Criar Quarto')
@section('content')
<div class="component">
  <h3>Criar Quarto</h3>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        {{-- <div class="x_title"></div> --}}
        <div class="x_content">
          <form action="{{ route('room.store') }}" method="POST" class="form-horizontal form-label-left">
             <input name="_token" id="token" type="hidden" value="{{ csrf_token() }}"/>
            <div class="form-group">
              <label for="" class="control-label col-md-3 col-sm-3 col-xs-12">Nome do quarto</label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <input type="text" class="form-control col-md-7 col-xs-12" required name="name_room" id="name_room">
              </div>
            </div>
            <div class="form-group">
              <label for="" class="control-label col-md-3 col-sm-3 col-xs-12">Ramal</label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <input type="phone" data-mask="'(99) 9 9999-9999'" class="form-control col-md-7 col-xs-12" required name="phone_room" id="phone_room">
              </div>
            </div>
            {{-- <div class="ln_solid"></div> --}}
            <div class="form-group">
              <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                <button type="submit" class="btn btn-success">Cadastrar</button>
                <button type="button" class="btn btn-primary">Cancelar</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<script>

</script>
@endsection

resources/views/admin/createUser.blade.php
@extends('layouts.app')
@section('title','Criar Usuário')
@section('content')
<div class="component">
  <h3>Criar Usuário</h3>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        {{-- <div class="x_title"></div> --}}
        @if(Session::has('success'))
        <div class="alert alert-success">
          <p>{{ Session::get('success') }}</p>
        </div>
        @endif
        
        @if(Session::has('error'))
        <div class="alert alert-danger">
          <p>{{ Session::get('error') }}</p>
        </div>
        @endif
        <div id="error_password" class="alert alert-danger" style="display: none">
          <p>Senhas não são iguais</p>
        </div>
        <div class="x_content">
          <form action="{{ route('user.store') }}" method="POST" class="form-horizontal form-label-left">
            <input name="_token" id="token" type="hidden" value="{{ csrf_token() }}"/>
            <div class="form-group">
              <label for="" class="control-label col-md-3 col-sm-3 col-xs-12">Nome</label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <input type="text" class="form-control col-md-7 col-xs-12" required name="name" id="name">
              </div>
            </div>
            <div class="form-group">
              <label for="" class="control-label col-md-3 col-sm-3 col-xs-12">Email</label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <input type="email" class="form-control col-md-7 col-xs-12" required name="user_email" id="user_email">
              </div>
            </div>
            <div class="form-group">
              <label for="" class="control-label col-md-3 col-sm-3 col-xs-12">Telefone</label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <input type="phone" class="form-control col-md-7 col-xs-12" required name="user_telefone" id="user_telefone">
              </div>
            </div>
            <div class="form-group">
              <label for="" class="control-label col-md-3 col-sm-3 col-xs-12">Tipo de usuário</label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <select class="form-control" id="type_user" name="type_user">
                  <option value="">Escolha o tipo de usuário</option>
                  <option value="1">Administrador</option>
                  <option value="2">Hóspede</option>
                </select>
              </div>
            </div>
            <div class="form-group" id="form_date" style="display: none">
              <label for="" class="control-label col-md-3 col-sm-3 col-xs-12">Data de check-out</label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <input type="text" class="form-control col-md-7 col-xs-12" required name="data_saida" id="data_saida">
              </div>
            </div>
            <div id="choose_room" class="form-group" style="display: none">
              <label for="" class="control-label col-md-3 col-sm-3 col-xs-12">Quarto</label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <select class="form-control" name="roomUser_id" id="roomUser_id">
                  <option value="">Qual o quarto que o hóspode se encontra:</option>
                  @foreach (range(1, 10) as $item)
                  <option value="{{ $item }}">Quarto {{ $item }}</option>
                  @endforeach
                </select>
              </div>
            </div>
            <div class="form-group">
              <label for="" class="control-label col-md-3 col-sm-3 col-xs-12">Senha</label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <input type="password" class="form-control col-md-7 col-xs-12" required name="password" id="form_password">
              </div>
            </div>
            <div class="form-group">
              <label for="" class="control-label col-md-3 col-sm-3 col-xs-12">Confirme a senha</label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <input type="password" class="form-control col-md-7 col-xs-12" required name="confirm_password" id="form_confirm_password">
              </div>
            </div>
            {{-- <div class="ln_solid"></div> --}}
            <div class="form-group">
              <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                <button type="submit" class="btn btn-success" id="submit_button">Submit</button>
                <button type="button" class="btn btn-primary">Cancelar</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<script>

  $('#type_user').change(function() {
    let valor = $(this).val()
    if (valor == '') {
      document.getElementById('choose_room').style.display = 'none'
      document.getElementById('form_date').style.display = 'none'
      document.getElementById('form_password').disabled = true
      document.getElementById('form_confirm_password').disabled = true
    }
    if (valor == 2) {
      document.getElementById('choose_room').style.display = 'block'
      document.getElementById('form_date').style.display = 'block'
      document.getElementById('form_password').disabled = false
      document.getElementById('form_confirm_password').disabled = false
    } 
    if(valor == 1) {
      document.getElementById('choose_room').style.display = 'none'
      document.getElementById('form_date').style.display = 'none'
      document.getElementById('form_password').disabled = false
      document.getElementById('form_confirm_password').disabled = false
    }
  })

  $('#confirm_password').change(function() {
    let valor = $(this).val()
    if (valor != $('#passowrd').val()) {
      document.getElementById('error_password').style.display = 'block'
      document.getElementById('submit_button').disabled = true
    } else {
      document.getElementById('error_password').style.display = 'none'
      document.getElementById('submit_button').disabled = false
    }
  })

</script>
@endsection

resources/views/admin/dashboard.blade.php
@extends('layouts.app')
@section('title','Dashboard')
@push('header-scripts-aux')
    <link rel="stylesheet" href="{{ asset('css/style.css')}}">

@endpush
@section('content')
<div class="component">
        @if (count($errors) > 0)
        <div class="alert alert-danger">
          <strong>Whoops!</strong> There were some problems with your input.<br><br>
          <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
          </ul>
        </div>
        @endif
        @if(session('success'))
        <div class="alert alert-success">
           {{ session('success') }}
        </div> 
      @endif
    <h3>Quartos</h3>
    <div id="card-room" style="display: grid; grid-template-columns: repeat(auto-fill, 200px); grid-gap: 1rem">
        @foreach ($rooms as $item)
            <div class="card" onclick='modalFunction({{ $item }})' style="width: 18rem; padding-top: 1rem; cursor: pointer;">
                <div class="card-body @if($item->status == 1) btn-warning @else btn-success @endif" style="border: 1px solid #ccc; padding: 1.25rem; border-radius: .5rem">
                    <h3 class="card-title text-center">Quarto {{ $item->name}}</h3>
                    <h5 class="card-subtitle mb-2 text-muted">Ramal: {{ $item->ramal }}</h5>
                    <h5 class="card-subtitle mb-2 text-muted">@if(isset($item->users[0]))Data de saída: {{$item->users[0]->data_saida }}@endif.</h5>
                   
                </div>
            </div>    
        @endforeach
    </div>
</div>
@include('admin.modalShow')
<script>
    async function modalFunction(obj) {
        if(obj.status == 0) {
            alert('Atenção não há hospedes neste quarto')
        } else {
            var html = ''
            for (let index = obj.users[0].photos.length -1; index >= 0 ; index--) {
                html += ' <div class="card col col-md-4 col-sm-6 col-lg-3">'
                html += `<img src="{{ asset('images/${obj.users[0].photos[index].filename}') }}" />`
                html += `<p>${obj.users[0].photos[index].name}</p>`
                html += '</div>'
            }
            // console.log(html)
            $("#img_card").html(html)
            $('#room_id').html("Quarto Nº "+obj.id)
            $('#room').val(obj.id)
            $('#room_name').html("Nome do quarto: "+obj.name)
            $('#modal-quarto').modal()
        }
    }

    $(document).ready(function() {

        $(".btn-success").click(function(){ 
            var html = $(".clone").html();
            $(".increment").after(html);
        });
  
        $("body").on("click",".btn-danger",function(){ 
            $(this).parents(".control-group").remove();
        });
  
      });
  

</script>
@endsection

resources/views/admin/modalShow.blade.php
<div id="modal-quarto" class="modal fade bd-example-modal-lg" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-body">
        <div class="modal-title col-md-12 col-sm-12 col-xs-12">
          
        </div>
        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
              <div class="dashboard_graph">
                <div class="row x_title">
                 
                  <div class="col-md-6">
                    <h4 id="room_id"></h4>
                  </div>
                </div>
                
                <div class="x_content">
                  <h4 id="room_name"></h4>
                  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident nam quia aut nobis facere quisquam consequuntur ullam odit nulla quasi fuga at alias est eligendi, ducimus magnam asperiores. Pariatur, officia.</p>
                  
                  {{-- <img src="{{ asset('') }}" alt=""> --}}
                  <form method="post" action="{{url('/admin/photo/store')}}" enctype="multipart/form-data">
                    {{csrf_field()}}
                    
                          <input type="text" style="display: none" id="room" name="room">
                          <div class="input-group control-group increment" >
                            <input type="file" name="filename[]" class="form-control">
                            <div class="input-group-btn"> 
                              <button class="btn btn-success" type="button"><i class="glyphicon glyphicon-plus"></i>Add</button>
                            </div>
                          </div>
                          <div class="clone hide">
                            <div class="control-group input-group" style="margin-top:10px">
                              <input type="file" name="filename[]" class="form-control">
                              <div class="input-group-btn"> 
                                <button class="btn btn-danger" type="button"><i class="glyphicon glyphicon-remove"></i> Remove</button>
                              </div>
                            </div>
                          </div>
                  
                          <button type="submit" class="btn btn-primary" style="margin-top:10px">Submit</button>
                    </form>  
                    <div id="photoRoom">
                      <div id="img_card" class="cards row">
                    </div>
                  </div> 
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>